---
- hosts: all
  sudo: true
  roles:
    - common


- hosts: hostmaster
  sudo: true
  roles:
    - mariadb
    - nginx
    - php
    - drush
    - { role: aegir-master, master_domain: aegir.cms-demo.ub.gu.se }


- hosts: webserver
  sudo: true
  roles:
    - mariadb
    - nginx
    - php
    - drush
    - aegir-slave

